name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: pip install --upgrade pip setuptools

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with django
      run: python manage.py test

