name: Python application

on: [push]

jobs:
  test-job:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
          POSTGRES_DB: demo
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with django
      env:
        NODE_INDEX: ${{ matrix.ci_node_index }}
      run: |
        if [[ "$NODE_INDEX" = "0" ]]; then
          python manage.py test
        elif [[ "$NODE_INDEX" = "1" ]]; then
          python manage.py runserver &
          npx cypress run --spec cypress/integration/simple.js
        fi

  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Migrate heroku db
      run: |
        echo "DATABASE_URL=postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@ec2-184-72-235-80.compute-1.amazonaws.com/dfiu7lp2jib90m" > .env
        echo "" >> .env

        python manage.py migrate
        python manage.py loaddata polls/fixture

    - name: Heroku login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a django-demo-erwin web

    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a django-demo-erwin web
